export const ActionType = {
    FETCH_MOVIES : "FETCH_MOVIES",
    SELECTED_MOVIES : "SELECTED_MOVIES",
    TOP_RATED_MOVIES : "TOP_RATED_MOVIES",
    FETCH_TVSHOWS : "FETCH_TVSHOWS",
    REMOVE_SELECTED_MOVIES : "REMOVE_SELECTED_MOVIES"
}

export const ActionCrew = {
    FETCH_CREW : "FETCH_CREW",
    SELECT_CREW : "SELECT_CREW",
    REMOVE_CREW : "REMOVE_CREW"
}

export const ActionPeople = {
    FETCH_PEOPLE : "FETCH_PEOPLE",
    SELECTED_PEOPLE : "SELECTED_PEOPLE",
    REMOVE_PEOPLE : "REMOVE_PEOPLE"
}

export const ActionPeopleCast = {
    FETCH_PEOPLE_CAST : "FETCH_PEOPLE_CAST",
    REMOVE_pEOPLE_CAST : "REMOVE_pEOPLE_CAST"
}
